# Generated by Django 5.1.4 on 2024-12-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mygutenberg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(unique=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, max_length=50, null=True)),
                ('publication_date', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
